### ISSUE TITLE
Disable logging style override by default

### ISSUE THREAD

**Issue by vladisavvv** [epam/ai-dial-sdk#43]
For example, we are now overriding the standard logging level for uvicorn.

**Comment by adubovik** [comment]
_Correction_: currently we do not override logging level for unicorn, but we do override format string to achieve uniformity between DIAL SDK logs and Uvicorn logs.

Back to the issue:

Uvicorn configures its [logging](https://github.com/encode/uvicorn/blob/master/uvicorn/config.py#L66) by default without requiring user input.

Why? Because Uvicorn is a platform on which you develop your server. It's crucial to see logs of incoming requests — this is the most important feature of a server.

Compare this with [OpenAI](https://github.com/openai/openai-python/blob/ec4511a6fa4862770cf14b2b58d3493e9bacb062/src/openai/_utils/_logs.py#L17), where logging is disabled by default but can be enabled if needed.

Which category does Dial SDK fall into? A framework or a third-party library? I believe it's the same as Uvicorn since the primary output of Dial SDK is a server application.

Therefore, we are well within our rights to set default log formats for Uvicorn as well, since in a sense, Uvicorn is part of Dial SDK.
